### ISSUE TITLE
call procedure

### ISSUE THREAD

**Issue by GrigoriyMo** [ForbesLindesay/sync-mysql#17]
Can You, please explain how to call the proc properly using your module? Thank You in advance!
For exmple i try to run the next:
`db.call(procs.registration, "hello");`
and have the next feedback from node:
```

TypeError: Expected args to be strings
    at Connection.call (/aut/ufo/node_modules/sync-mysql/lib/index.js:43:15)
    at Object.<anonymous> (/aut/ufo/lib/test.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by charmingny** [comment]
example from my project 

 this.m_connection = new MySql({
            host: 'localhost',
            user: 'root',
            database: 'test',        
            password: ''
            });

const sql:string = "call p_update_winlose(" + 
                                                            "0," +
                                                            "'"+ Playerstr + "'," +
                                                            "'"+ CoinStr + "'," +
                                                            "@out_result," +
                                                            "@out_ids," +
                                                            "@out_coins" +                                                          
                                                            ")";

   const result    = this.m_connection.query(sql);
   const query     = this.m_connection.query("SELECT @out_ids AS pids, @out_coins AS coins");
